@baseUrl = http://localhost:8000


### Signup

POST {{baseUrl}}/auth/sign-up/email HTTP/1.1
Content-Type: application/json

{
  "json": {
    "email": "test@dev.com",
    "name": "Test User",
    "password": "passwords"
  }
}


### Login

# @name login

POST {{baseUrl}}/auth/sign-in/email HTTP/1.1
Content-Type: application/json

{
  "email": "test@dev.com",
  "password": "testpass"
}

> ./post-login.lua


### Get Current User

GET {{baseUrl}}/api/user/whoami HTTP/1.1
Content-Type: application/json
Cookie: better-auth.session_token={{session_token}}
Cookie: better-auth.session_data={{session_data}}
